name: Run go tests

on:
  push:
    branches: 
      - '*'
    tags: 
      - '!v*'
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'ready_for_review']

jobs:
  golangci:
      name: "go test"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v4
          with:
            go-version: 1.21
            cache: true
        - name: 'go lint'
          uses: golangci/golangci-lint-action@v3
          with:
            version: latest
        - name: 'go test'
          run: go test ./...
        