name: Check for vulnerabilities

on:
  schedule:
    - cron: '25 8 * * *'
  
jobs:
  govulncheck:
      name: "go vulncheck"
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-go@v4
            with:
                go-version: 1.21
                cache: true
          - name: 'go vulncheck'
            uses: golang/govulncheck-action@v1
            with:
                go-version-input: 1.21
                go-package: ./...